### ISSUE TITLE
CyclomaticComplexity's severity can only be ERROR or IGNORE

### ISSUE THREAD

**Issue by DalekCraft2** [vshaxe/vscode-checkstyle#22]
Trying to set the severity for CyclomaticComplexity to `WARNING` or `INFO` results in it behaving as if it was set to `ERROR`. Not much else to add, besides the fact that I am using the latest update which changed something with severities.

I've also tried getting rid of `defaultSeverity` and getting rid of the `severity` tag entirely, but neither fixed it.

**Comment by AlexHaxe** [comment]
`CyclomaticComplexity` does not use `severity`. it uses `thresholds` array to define at which point a complexity value is an ignore, info, warning or error message. 

note: `severity` field exists but only because of inheritance from base class. it's not read by design. other checks have true and false decisions, but `CyclomaticComplexity` check produces an integer value where a certain range either means "it's ok" or "slightly bad" or "real bad". so a single value wouldn't work.

[see docs](http://haxecheckstyle.github.io/docs/haxe-checkstyle/cyclomaticcomplexity.html)
